#!/usr/bin/bash
cp /public/hstore5/proteome/pipeline/script/project_r_plotting/PCA_plotting.R ./;cp /public/hstore5/proteome/pipeline/script/project_r_plotting/runpcaplotting.sh ./;sh runpcaplotting.sh
