#!/usr/bin/bash
cp /public/hstore5/proteome/pipeline/script/project_r_plotting/Ubiquitinated_Labelfree_R_Plotting.R ./;cp /public/hstore5/proteome/pipeline/script/project_r_plotting/runubiqu_plotting.sh ./;bash runubiqu_plotting.sh
